
//测试mybatis集成示范代码
GET http://localhost:8080/ebookTest/list

###

GET http://localhost:8080/ebookTest/listByName?name=教程

###

GET http://localhost:8080/ebookTest/listByName?name=Spring

###

GET http://localhost:8080/ebookTest/listByEntity?name=Spring

###

GET http://localhost:8080/ebookTest/listResp?name=Spring

###

GET http://localhost:8080/ebookTest/listResp

###

GET http://localhost:8080/ebookTest/listResp?page=1&size=2

###

GET http://localhost:8080/ebook/list?name=Spring

###

GET http://localhost:8080/ebook/list #制作了CopyUtil来copy对象

###

GET http://localhost:8080/ebook/list?page=1&size=2

###

POST http://localhost:8080/ebook/save

{}

###

GET http://localhost:8080/ebook/list?page=1&size=10001
